
line-length = 120


[lint]
select = ["I","E4","E5", "E7", "E9", "F","B","Q","PYI"]
ignore = ["E701","Q000"]
    
    
[lint.isort]
force-single-line = false
combine-as-imports = true
#float-to-top=true

[analyze]
detect-string-imports = true
